// Scripted pipeline
node {
    def commit_id
    def ciContainer
    stage('Preparation') {
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"
        commit_id = readFile('.git/commit-id').trim()
        ciContainer = docker.build("flyup:${commit_id}")
    }
    stage('Install dependencies in image') {
        ciContainer.inside{
            sh 'npm i'
        }
    }
    stage('Lint') {
        sh 'echo ...Linting ... coming soon && pwd && ls -la '
    }
    stage('Test') {
        ciContainer.inside ('--env-file .env.test') {
            sh 'npm test'
        }
    }
}
